### ISSUE TITLE
This is linked to from imsglobal.org as example of source code for LTI

### ISSUE THREAD

**Issue by jeffreybrowning** [nsip/HITS-LTIJS#1]
But this seems to be an incomplete project. Is this currently being worked on?

**Comment by opoudjis** [comment]
Sorry, @jeffreybrowning, I just saw this ticket. (I was the analyst on the project rather than the developer.) As you will have inferred, this project has not been worked on in quite a while. We demonstrated it to IMS as a proof of concept, allowing LTI to consume data from SIF via REST. There has been no followup since, although the project may be reactivated in the future.
